---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: treadmill
  namespace: treadmill
  labels:
    app.kubernetes.io/name: treadmill
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: treadmill
  template:
    metadata:
      labels:
        app.kubernetes.io/name: treadmill
    spec:
      containers:
      - name: treadmill
        image: registry.cloud.cbh.kth.se/treadmill/treadmill
        envFrom:
        - configMapRef:
            name: treadmill-configmap
